#ifndef QT_H
#define QT_H
    #include <QtCore/QCoreApplication>
    #include <QtCore/QCommandLineParser>
    #include <QtCore/QCommandLineOption>
    #include <QtCore/QObject>
    #include <QtCore/QList>
    #include <QtCore/QByteArray>
    #include <QtCore/QMap>
    #include <QtCore/QString>
    #include <QtCore/QDebug>
    #include <QTcpServer>
    #include <QTcpSocket>
    #include <QMetaType>
    #include <QSet>
    #include <QStandardPaths>
    #include <QDataStream>
    #include <QTextStream>
#endif 